package ml.memelau.catcher.server.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table error_event
 */
@ApiModel
public class ErrorEvent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_event.id
     *
     * @mbg.generated
     */
    @ApiModelProperty("报警ID")
    private Integer id;

    /**
     * Database Column Remarks:
     *   事件类型（区分不同类型的错误事件，如java，java_web，js等）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_event.event_type
     *
     * @mbg.generated
     */
    private String eventType;

    /**
     * Database Column Remarks:
     *   严重程度（0，1，2，3）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_event.severity
     *
     * @mbg.generated
     */
    private Integer severity;

    /**
     * Database Column Remarks:
     *   错误信息类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_event.error_type
     *
     * @mbg.generated
     */
    @ApiModelProperty("错误信息类型")
    private String errorType;

    /**
     * Database Column Remarks:
     *   应用详情
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_event.app_name
     *
     * @mbg.generated
     */
    @ApiModelProperty("应用名称")
    private String appName;

    /**
     * Database Column Remarks:
     *   环境
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_event.env
     *
     * @mbg.generated
     */
    @ApiModelProperty("环境名")
    private String env;

    /**
     * Database Column Remarks:
     *   主机名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_event.hostname
     *
     * @mbg.generated
     */
    @ApiModelProperty("主机名")
    private String hostname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_event.ip
     *
     * @mbg.generated
     */
    @ApiModelProperty("ip")
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_event.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     * Database Column Remarks:
     *   处理人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_event.handler_id
     *
     * @mbg.generated
     */
    private Integer handlerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_event.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_event.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   处理状态
     *   0 待处理（只能选忽略或处理中）
     *   1 处理中（只能选忽略或待部署）
     *   2 待部署（只能选已处理）
     *   3 已处理
     *   -1 忽略（只能选处理中）
     *   -2 复现
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_event.handling_state
     *
     * @mbg.generated
     */
    @ApiModelProperty("处理状态 *   处理状态\n" +
            "     *   0 待处理（只能选忽略或处理中）\n" +
            "     *   1 处理中（只能选忽略或待部署）\n" +
            "     *   2 待部署（只能选已处理）\n" +
            "     *   3 已处理\n" +
            "     *   -1 忽略（只能选处理中）\n" +
            "     *   -2 复现")
    private Integer handlingState;

    /**
     * Database Column Remarks:
     *   处理次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_event.handling_times
     *
     * @mbg.generated
     */
    @ApiModelProperty("处理时间")
    private Integer handlingTimes;

    /**
     * Database Column Remarks:
     *   详情散列（事件类型，错误类型，信息详情，环境，应用名称，项目组id）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_event.event_hash
     *
     * @mbg.generated
     */
    private String eventHash;

    /**
     * Database Column Remarks:
     *   错误详情
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_event.error_message
     *
     * @mbg.generated
     */
    @ApiModelProperty("错误详情")
    private String errorMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table error_event
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_event.id
     *
     * @return the value of error_event.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    public ErrorEvent withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_event.id
     *
     * @param id the value for error_event.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_event.event_type
     *
     * @return the value of error_event.event_type
     *
     * @mbg.generated
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    public ErrorEvent withEventType(String eventType) {
        this.setEventType(eventType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_event.event_type
     *
     * @param eventType the value for error_event.event_type
     *
     * @mbg.generated
     */
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_event.severity
     *
     * @return the value of error_event.severity
     *
     * @mbg.generated
     */
    public Integer getSeverity() {
        return severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    public ErrorEvent withSeverity(Integer severity) {
        this.setSeverity(severity);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_event.severity
     *
     * @param severity the value for error_event.severity
     *
     * @mbg.generated
     */
    public void setSeverity(Integer severity) {
        this.severity = severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_event.error_type
     *
     * @return the value of error_event.error_type
     *
     * @mbg.generated
     */
    public String getErrorType() {
        return errorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    public ErrorEvent withErrorType(String errorType) {
        this.setErrorType(errorType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_event.error_type
     *
     * @param errorType the value for error_event.error_type
     *
     * @mbg.generated
     */
    public void setErrorType(String errorType) {
        this.errorType = errorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_event.app_name
     *
     * @return the value of error_event.app_name
     *
     * @mbg.generated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    public ErrorEvent withAppName(String appName) {
        this.setAppName(appName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_event.app_name
     *
     * @param appName the value for error_event.app_name
     *
     * @mbg.generated
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_event.env
     *
     * @return the value of error_event.env
     *
     * @mbg.generated
     */
    public String getEnv() {
        return env;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    public ErrorEvent withEnv(String env) {
        this.setEnv(env);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_event.env
     *
     * @param env the value for error_event.env
     *
     * @mbg.generated
     */
    public void setEnv(String env) {
        this.env = env;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_event.hostname
     *
     * @return the value of error_event.hostname
     *
     * @mbg.generated
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    public ErrorEvent withHostname(String hostname) {
        this.setHostname(hostname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_event.hostname
     *
     * @param hostname the value for error_event.hostname
     *
     * @mbg.generated
     */
    public void setHostname(String hostname) {
        this.hostname = hostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_event.ip
     *
     * @return the value of error_event.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    public ErrorEvent withIp(String ip) {
        this.setIp(ip);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_event.ip
     *
     * @param ip the value for error_event.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_event.group_id
     *
     * @return the value of error_event.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    public ErrorEvent withGroupId(Integer groupId) {
        this.setGroupId(groupId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_event.group_id
     *
     * @param groupId the value for error_event.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_event.handler_id
     *
     * @return the value of error_event.handler_id
     *
     * @mbg.generated
     */
    public Integer getHandlerId() {
        return handlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    public ErrorEvent withHandlerId(Integer handlerId) {
        this.setHandlerId(handlerId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_event.handler_id
     *
     * @param handlerId the value for error_event.handler_id
     *
     * @mbg.generated
     */
    public void setHandlerId(Integer handlerId) {
        this.handlerId = handlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_event.create_time
     *
     * @return the value of error_event.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    public ErrorEvent withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_event.create_time
     *
     * @param createTime the value for error_event.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_event.update_time
     *
     * @return the value of error_event.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    public ErrorEvent withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_event.update_time
     *
     * @param updateTime the value for error_event.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_event.handling_state
     *
     * @return the value of error_event.handling_state
     *
     * @mbg.generated
     */
    public Integer getHandlingState() {
        return handlingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    public ErrorEvent withHandlingState(Integer handlingState) {
        this.setHandlingState(handlingState);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_event.handling_state
     *
     * @param handlingState the value for error_event.handling_state
     *
     * @mbg.generated
     */
    public void setHandlingState(Integer handlingState) {
        this.handlingState = handlingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_event.handling_times
     *
     * @return the value of error_event.handling_times
     *
     * @mbg.generated
     */
    public Integer getHandlingTimes() {
        return handlingTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    public ErrorEvent withHandlingTimes(Integer handlingTimes) {
        this.setHandlingTimes(handlingTimes);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_event.handling_times
     *
     * @param handlingTimes the value for error_event.handling_times
     *
     * @mbg.generated
     */
    public void setHandlingTimes(Integer handlingTimes) {
        this.handlingTimes = handlingTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_event.event_hash
     *
     * @return the value of error_event.event_hash
     *
     * @mbg.generated
     */
    public String getEventHash() {
        return eventHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    public ErrorEvent withEventHash(String eventHash) {
        this.setEventHash(eventHash);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_event.event_hash
     *
     * @param eventHash the value for error_event.event_hash
     *
     * @mbg.generated
     */
    public void setEventHash(String eventHash) {
        this.eventHash = eventHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_event.error_message
     *
     * @return the value of error_event.error_message
     *
     * @mbg.generated
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    public ErrorEvent withErrorMessage(String errorMessage) {
        this.setErrorMessage(errorMessage);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_event.error_message
     *
     * @param errorMessage the value for error_event.error_message
     *
     * @mbg.generated
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ErrorEvent other = (ErrorEvent) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEventType() == null ? other.getEventType() == null : this.getEventType().equals(other.getEventType()))
            && (this.getSeverity() == null ? other.getSeverity() == null : this.getSeverity().equals(other.getSeverity()))
            && (this.getErrorType() == null ? other.getErrorType() == null : this.getErrorType().equals(other.getErrorType()))
            && (this.getAppName() == null ? other.getAppName() == null : this.getAppName().equals(other.getAppName()))
            && (this.getEnv() == null ? other.getEnv() == null : this.getEnv().equals(other.getEnv()))
            && (this.getHostname() == null ? other.getHostname() == null : this.getHostname().equals(other.getHostname()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()))
            && (this.getGroupId() == null ? other.getGroupId() == null : this.getGroupId().equals(other.getGroupId()))
            && (this.getHandlerId() == null ? other.getHandlerId() == null : this.getHandlerId().equals(other.getHandlerId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getHandlingState() == null ? other.getHandlingState() == null : this.getHandlingState().equals(other.getHandlingState()))
            && (this.getHandlingTimes() == null ? other.getHandlingTimes() == null : this.getHandlingTimes().equals(other.getHandlingTimes()))
            && (this.getEventHash() == null ? other.getEventHash() == null : this.getEventHash().equals(other.getEventHash()))
            && (this.getErrorMessage() == null ? other.getErrorMessage() == null : this.getErrorMessage().equals(other.getErrorMessage()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEventType() == null) ? 0 : getEventType().hashCode());
        result = prime * result + ((getSeverity() == null) ? 0 : getSeverity().hashCode());
        result = prime * result + ((getErrorType() == null) ? 0 : getErrorType().hashCode());
        result = prime * result + ((getAppName() == null) ? 0 : getAppName().hashCode());
        result = prime * result + ((getEnv() == null) ? 0 : getEnv().hashCode());
        result = prime * result + ((getHostname() == null) ? 0 : getHostname().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
        result = prime * result + ((getHandlerId() == null) ? 0 : getHandlerId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getHandlingState() == null) ? 0 : getHandlingState().hashCode());
        result = prime * result + ((getHandlingTimes() == null) ? 0 : getHandlingTimes().hashCode());
        result = prime * result + ((getEventHash() == null) ? 0 : getEventHash().hashCode());
        result = prime * result + ((getErrorMessage() == null) ? 0 : getErrorMessage().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_event
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eventType=").append(eventType);
        sb.append(", severity=").append(severity);
        sb.append(", errorType=").append(errorType);
        sb.append(", appName=").append(appName);
        sb.append(", env=").append(env);
        sb.append(", hostname=").append(hostname);
        sb.append(", ip=").append(ip);
        sb.append(", groupId=").append(groupId);
        sb.append(", handlerId=").append(handlerId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", handlingState=").append(handlingState);
        sb.append(", handlingTimes=").append(handlingTimes);
        sb.append(", eventHash=").append(eventHash);
        sb.append(", errorMessage=").append(errorMessage);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}