package ml.memelau.catcher.server.mapper;

import java.util.List;
import ml.memelau.catcher.server.model.AppGroupMember;
import ml.memelau.catcher.server.model.AppGroupMemberExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface AppGroupMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group_member
     *
     * @mbg.generated
     */
    long countByExample(AppGroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group_member
     *
     * @mbg.generated
     */
    int insert(AppGroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group_member
     *
     * @mbg.generated
     */
    int insertSelective(AppGroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group_member
     *
     * @mbg.generated
     */
    List<AppGroupMember> selectByExampleWithRowbounds(AppGroupMemberExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group_member
     *
     * @mbg.generated
     */
    List<AppGroupMember> selectByExample(AppGroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group_member
     *
     * @mbg.generated
     */
    AppGroupMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group_member
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AppGroupMember record, @Param("example") AppGroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group_member
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AppGroupMember record, @Param("example") AppGroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppGroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppGroupMember record);
}