package ml.memelau.catcher.server.mapper;

import ml.memelau.catcher.server.model.AppGroup;
import ml.memelau.catcher.server.model.AppGroupExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

@Mapper
public interface AppGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group
     *
     * @mbg.generated
     */
    long countByExample(AppGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group
     *
     * @mbg.generated
     */
    int insert(AppGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group
     *
     * @mbg.generated
     */
    int insertSelective(AppGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group
     *
     * @mbg.generated
     */
    List<AppGroup> selectByExampleWithBLOBsWithRowbounds(AppGroupExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group
     *
     * @mbg.generated
     */
    List<AppGroup> selectByExampleWithBLOBs(AppGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group
     *
     * @mbg.generated
     */
    List<AppGroup> selectByExampleWithRowbounds(AppGroupExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group
     *
     * @mbg.generated
     */
    List<AppGroup> selectByExample(AppGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group
     *
     * @mbg.generated
     */
    AppGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AppGroup record, @Param("example") AppGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") AppGroup record, @Param("example") AppGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AppGroup record, @Param("example") AppGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(AppGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppGroup record);
}